### ISSUE TITLE
Expand TweakScaleCompanion_NF#2 (suppress warnings due empty configs)

### ISSUE THREAD

**Issue by 7ranceaddic7** [net-lisias-ksp/TweakScaleCompanion_FS#10]
Details here: #net-lisias-ksp/TweakScaleCompanion_NF#2

**Comment by Lisias** [comment]
DAMN.

I completely forgot about this one. Unfortunately, I ended up working it on https://github.com/TweakScale/Companion/issues/15 .

My apologies!!!
