### ISSUE TITLE
TweakScaleCompanion.FS

### ISSUE THREAD

**Issue by 7ranceaddic7** [net-lisias-ksp/TweakScaleCompanion_FS#8]
I don't know if this would cause any problem or if you did this on purpose, but Imma highlight it simply because it is unconventional for you.

Everything else is named TweakScaleCompanion_XXX (underscore)

The naming convention is even violated within the TweakScaleCompanion for FS.

**Comment by Lisias** [comment]
Hi, thanks for the report.

On this specific case, it's the other way around. Due a rush on the putting things on the wild, I didn't gave enough though on the naming convention, and ended up having the following situation:

* NetKan identifiers need to use dash `-` so, `TweakScaleCompanion-FS` .
* Source code need to use a dot `.` so, `TweakScaleCompanion.FS` .
* There are places that don't like dots and dashes, so an underscore `_` will be used  there. So`TweakScaleCompanion_FS`.

Pretty messy, uh? :)

In a way or another, it's not a bug. Yet. :)

If you find something else weird, however, don't hesitate on open an issue. Sooner or later you will be right! :D
